# -*- coding: utf-8 -*-
"""Final Project Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_ZMCfT1Svo-TE6swxOfN1fhB3C0x9AT
"""

!pip install -q google-generativeai pandas

import pandas as pd
import google.generativeai as genai
from google.colab import files

genai.configure(api_key="AIzaSyAZJeItWgA5TT9KWeHpoI1N4PpxtC6Qpq4")

uploaded = files.upload()

csv_path = list(uploaded.keys())[0]
df = pd.read_csv(csv_path)

print("\n✅ File berhasil dimuat!")
print(df.head())

model = genai.GenerativeModel(
    model_name="gemini-2.5-flash",
    generation_config={
        "temperature": 0.3,
        "max_output_tokens": 512,
        "top_p": 1.0,
        "top_k": 40
    }
)

def chatbot(query):
    prompt = f"""
    Kamu adalah asisten monitoring Access Point.
    Berikut data Access Point dari dashboard:
    {context_text}

    Berdasarkan data di atas, jawab pertanyaan berikut dengan singkat, jelas, dan berbasis data:
    {query}
    """
    try:
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        return f"⚠️ Terjadi error saat memproses pertanyaan: {str(e)}"

print("\n🤖 Chatbot siap digunakan! Ketik 'exit' untuk berhenti.\n")

while True:
    user_input = input("User: ")
    if user_input.lower() in ["exit", "quit", "keluar"]:
        print("Chatbot: Sampai jumpa!")
        break
    print("Chatbot:", chatbot(user_input))